import ast
import json
import logging
from typing import Dict, Any, Optional, Tuple, Callable, Awaitable
from dataclasses import dataclass, field

# Reuse BaseSubAgent from core/orchestrator.py
from core.orchestrator import BaseSubAgent

logger = logging.getLogger("SaphiraEvaluator")


@dataclass
class EvaluationReport:
    is_valid: bool
    score: float  # Quality score between 0.0 and 1.0
    issues: list[str] = field(default_factory=list)
    suggested_fix: Optional[str] = None


class EvaluatorAgent(BaseSubAgent):
    """
    Validation and Self-Correction Agent for Saphira.
    Evaluates code syntax, response structure, and semantic fidelity.
    """

    def __init__(self, llm_critic_func: Optional[Callable[[str, str], Awaitable[str]]] = None):
        super().__init__(
            name="evaluator",
            description="Validates agent outputs, checks syntax, and drives self-correcting retry loops."
        )
        self.llm_critic_func = llm_critic_func

    async def execute(self, task_prompt: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Executes validation on target content provided in the context dict.
        Context structure expected:
          - target_content: str (The output generated by primary agent)
          - expected_type: str ("code", "json", "text")
          - original_prompt: str (User's original instruction)
        """
        if not context or "target_content" not in context:
            return {"status": "error", "message": "Evaluator requires 'target_content' in context."}

        content = context.get("target_content", "")
        content_type = context.get("expected_type", "text")
        original_prompt = context.get("original_prompt", task_prompt)

        # Step 1: Deterministic Static Check
        report = self.run_static_checks(content, content_type)

        # Step 2: Semantic / LLM Critic Check (if static passes and LLM critic is provided)
        if report.is_valid and self.llm_critic_func:
            critic_report = await self.run_llm_critic(original_prompt, content)
            report.is_valid = critic_report.is_valid
            report.score = critic_report.score
            report.issues.extend(critic_report.issues)
            report.suggested_fix = critic_report.suggested_fix

        return {
            "is_valid": report.is_valid,
            "quality_score": report.score,
            "issues": report.issues,
            "suggested_fix": report.suggested_fix
        }

    # --- Static Inspection Engines ---

    def run_static_checks(self, content: str, content_type: str) -> EvaluationReport:
        """Executes zero-latency static checks based on expected content format."""
        if content_type == "code" or "```python" in content:
            return self._validate_python_syntax(content)
        elif content_type == "json" or "```json" in content:
            return self._validate_json_structure(content)
        else:
            # Default basic text validation
            if not content.strip():
                return EvaluationReport(is_valid=False, score=0.0, issues=["Output is empty."])
            return EvaluationReport(is_valid=True, score=1.0, issues=[])

    def _validate_python_syntax(self, code_str: str) -> EvaluationReport:
        """Parses Python code into an AST to verify syntax validity without execution."""
        # Extract code block if wrapped in markdown standard
        raw_code = code_str
        if "```python" in code_str:
            raw_code = code_str.split("```python")[1].split("```")[0].strip()
        elif "```" in code_str:
            raw_code = code_str.split("```")[1].split("```")[0].strip()

        try:
            ast.parse(raw_code)
            return EvaluationReport(is_valid=True, score=1.0, issues=[])
        except SyntaxError as e:
            error_msg = f"SyntaxError on line {e.lineno}, col {e.offset}: {e.msg}"
            logger.warning(f"Static code validation failed: {error_msg}")
            return EvaluationReport(
                is_valid=False,
                score=0.2,
                issues=[error_msg],
                suggested_fix=f"Fix syntax error near line {e.lineno}: '{e.text.strip() if e.text else ''}'"
            )

    def _validate_json_structure(self, json_str: str) -> EvaluationReport:
        """Verifies if response conforms to valid JSON standard."""
        raw_json = json_str
        if "```json" in json_str:
            raw_json = json_str.split("```json")[1].split("```")[0].strip()
        elif "```" in json_str:
            raw_json = json_str.split("
      
